### DISCUSSION TITLE
Github Actions not considered a Pull Request

### DISCUSSION THREAD

**Discussion by saturnflyer** [danger/danger#1408] [Q&A] [answered]
I'm setting up danger in a repository but I'm getting a message in my GitHub actions.
```
Not a GitHubActions Pull Request - skipping `danger` run.
```
I've got a step defined in my ci config
```
      - name: Danger
        uses: MeilCli/danger-action@v5.6.0
        with:
          danger_file: "Dangerfile"
          danger_id: "whatever"
          danger_version: "9.0.0"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

And as far as I understand, since this is running on Github Actions, all of the required ENV vars exist. 
I added a step to output the contexts of ENV and can verify that all the required variables are there and set.

How can I best debug this issue? Or is there something obviously missing for me?

Thanks!
