### ISSUE TITLE
Ruby LoadError: cannot load such file

### ISSUE THREAD

**Issue by muuvmuuv** [danger/danger#1015]
# Report

## What did you do?

GitLab CI run `danger`
GitLab CI runs on docker container with alpine OS

## What did you expect to happen?

I don't know

## What happened instead?

```console
$ danger
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- json (LoadError)
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/gems/2.5.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache/storage.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/gems/2.5.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/gems/2.5.0/gems/danger-5.6.6/lib/danger/commands/local.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/gems/2.5.0/gems/danger-5.6.6/lib/danger/commands/runner.rb:4:in `<class:Runner>'
	from /usr/lib/ruby/gems/2.5.0/gems/danger-5.6.6/lib/danger/commands/runner.rb:2:in `<module:Danger>'
	from /usr/lib/ruby/gems/2.5.0/gems/danger-5.6.6/lib/danger/commands/runner.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/gems/2.5.0/gems/danger-5.6.6/lib/danger.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/gems/2.5.0/gems/danger-5.6.6/bin/danger:4:in `<top (required)>'
	from /usr/bin/danger:23:in `load'
	from /usr/bin/danger:23:in `<main>'
ERROR: Job failed: exit code 1
```

## Your Environment

* Which CI are you running on? Gitlab CI
* Are you running the latest version of Danger? Yes
* What is your Dangerfile?

```ruby
message("TEST")
```

.gitlab-ci.yml

```yml
variables:
  DANGER_GITLAB_API_TOKEN: "XXX"
  DANGER_GITLAB_HOST: "XXX"
  DANGER_GITLAB_API_BASE_URL: "XXX"

stages:
  - test

before_script:
  - apk add --update nodejs nodejs-npm ruby git
  - gem install danger danger-prose --no-ri --no-rdoc
  
danger:
  environment: Development
  stage: test
  script:
    - danger
```
