### ISSUE TITLE
Running two times Danger in same Pipelines report be covered

### ISSUE THREAD

**Issue by marcuswu0814** [danger/danger#1069]
# Report

## What did you do?

I using danger with gitlab-ci, and I had two Dangerfiles.

First named `Dangerfile`
```ruby
warn("Big MR") if git.lines_of_code > 500

swiftlint.lint_all_files = true
swiftlint.lint_files
```

Another named `DangerfileForCov`
```ruby
xcov.report(
   scheme: 'MyScheme',
   workspace: 'MyWorkspace.xcworkspace',
   minimum_coverage_percentage: 10.0
)
```

And my `.gitlab-ci.yml` like this:
```yml
stages:
  - danger
  - test
  - coverage-report

danger:
  stage: danger
  script: 
    - danger --fail-on-errors=true --dangerfile=Danger/Dangerfile --new-comment
  tags:
    - iOS
    
test:
  stage: test
  script:
    - fastlane test
  tags:
    - iOS

report:
  stage: coverage-report
  script:
    - pod install
    - danger --dangerfile=Danger/DangerfileForCov --new-comment
  tags:
    - iOS
```

I want to lint first and fail the build if lint had some error.
And after running the stage `test`, using `coverage-report` stage and using danger to report coverage data. 

## What did you expect to happen?

Two separate comment from my bot account. One reported this lint issue, another reported  code coverage. 

## What happened instead?

My coverage report comment cover the lint report comment. ` --new-comment` seems not working.

Is there had any solution can avoid this issue and running lint first?

## Your Environment

* Which CI are you running on?
GitLab-CI
* Are you running the latest version of Danger?
5.11.1
