### ISSUE TITLE
Running yarn danger local yields error

### ISSUE THREAD

**Issue by doronkatz** [danger/danger#1174]
# Report

## What did you do?

ℹ Please replace this with what you did.
`yarn danger local`

## What did you expect to happen?

Run on docker image (via bitbucket pipelines) and complete successfully.

## What happened instead?

```
root@893d1e34f18f:/app# yarn danger local
yarn run v1.19.1
$ /app/node_modules/.bin/danger local
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:262:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:12)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn git',
  path: 'git',
  spawnargs: [ 'diff', 'master...HEAD' ]
}
error Command failed with exit code 1.
```

## Your Environment
Bitbucket pipelines. Running latest version of Danger.

  ```ruby
import DangerSwiftCoverage
Coverage.spmCoverage(minimumCoverage: 50)
  ```
The bitbucket-pipelines file step contains:
```yml
- step: &step-coverage
      name: Danger Coverage
      image: node:slim
      caches:
        - node
      script:
        - yarn add danger
        - yarn danger ci
```
