### ISSUE TITLE
Is there any way to run Danger with GitHub Actions `pull_request_review` event?

### ISSUE THREAD

**Issue by andooown** [danger/danger#1228]
# Report

I'd like to run Danger on GitHub Actions with other than `pull_request` event (for example, `pull_request_review`). However, Danger skip running.

It seems that it caused by here.
https://github.com/danger/danger/blob/057037ce7bd7e7bca5a9ff2c5bf43cfde37cac3b/lib/danger/ci_source/github_actions.rb#L23-L25

Is there any way to run Danger with `pull_request_review` event on GitHub Actions?

## What did you do?

Run Danger on GitHub Actions with `pull_request_review` event: `bundle exec danger`

## What did you expect to happen?

Running Danger with other than `pull_request` event  same as it.

## What happened instead?

Danger said "Not a GitHubActions Pull Request - skipping `danger` run." and skipped running.

![image](https://user-images.githubusercontent.com/19662625/81766517-3f777f00-9511-11ea-827b-3de16433e4e2.png)

## Your Environment

- GitHub Actions
- Danger: 6.3.0
  - Installed via Bundler

```yml
name: Danger
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  pull_request_review:
  push:
    branches:
      - feature/*
jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
    - name: Setup gems
      run: |
        gem install bundler -v "1.16.1"
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run Danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec danger
```

**Comment by orta** [comment]
I think danger-js supports this, and maybe with some work you could get Danger Ruby to support this by looking up the PR number and then making it do the normal pull request work

**Comment by andooown** [comment]
@orta 
Thanks.

> maybe with some work you could get Danger Ruby to support this by looking up the PR number and then making it do the normal pull request work

Which do you mean?
1. Run Danger by `danger pr <pr_url>` command.
    - I think this can't post to remote PR.
2. Run Danger after collect required data (for example, `GITHUB_REPOSITORY`, required in following code) and set `GITHUB_EVENT_NAME` env as `pull_request`.
https://github.com/danger/danger/blob/057037ce7bd7e7bca5a9ff2c5bf43cfde37cac3b/lib/danger/ci_source/github_actions.rb#L31-L41

**Comment by orta** [comment]
I think 2 would work!

**Comment by andooown** [comment]
Thanks!

I will try 2, and share the result here.

**Comment by andooown** [comment]
My final GitHub Actions workflow is below.

```yaml
name: Danger
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  pull_request_review:
  # I couldn't run in `push` event yet!
  #push:
  #  branches:
  #    - feature/*
jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
    - name: Setup gems
      run: |
        gem install bundler -v "1.16.1"
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run Danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        event_path=${{ github.event_path }}

        if [ $GITHUB_EVENT_NAME = "pull_request_review" ]; then
          echo "Override event json file for pull_request_review event."

          event_path="event.json"
          cat ${{ github.event_path }} | jq '. |= .+ {"number": .pull_request.number}' > $event_path 
        fi

        GITHUB_EVENT_PATH=$event_path GITHUB_EVENT_NAME=pull_request bundle exec danger
```

It seems to be working properly!
![image](https://user-images.githubusercontent.com/19662625/83092615-a2a00e80-a0d8-11ea-8875-725f845d6623.png)

However, I think it is just work around.
Is there any plan to support `pull_request_review` in Danger?
