### ISSUE TITLE
GitLab CI Running Danger Returns Permission Error

### ISSUE THREAD

**Issue by AlexandreOkita** [danger/danger#1296]
# Report

## What did you do?

Run `bundle exec danger` in GitLab CI (self hosted) for a merge request job

## What did you expect to happen?

Running my Dangerfile without it crashing.

## What happened instead?

Returns a permission error:
```
Gitlab::Error::Forbidden: Server responded with code 403, message: <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
You don't have permission to access "http&#58;&#47;&#47;my&#46;company&#46;com&#46;br&#47;api&#47;v4&#47;projects&#47;path&#to&#my&#failing&#45;project&#47;merge&#95;requests&#47;8&#47;notes" on this server.<P>
Reference&#32;&#35;18&#46;ca386368&#46;1616416935&#46;50067188
</BODY>
</HTML>
```

## Your Environment

* Which CI are you running on? GitLab CI (Self Hosted)
* Are you running the latest version of Danger? Yes
* What is your Dangerfile?

  ```ruby
  if (!danger.gitlab.mr.title.contains("WIP")) {
    warn("PR is not considered WIP!")
  }
  ```
* GitLab Danger Job

  ```YAML
  danger:
    stage: .pre
    tags:
        - my-self-hosted-machine
    before_script:
        - bundle install
    script:
        - export CI_PROJECT_PATH=$CI_PROJECT_ID
        - bundle exec danger
    rules:
        - if: $CI_MERGE_REQUEST_IID
  ```
* Gemfile - Just installing danger-gitlab and other unrelated gems
* CI/CD variables: DANGER_GITLAB_API_TOKEN with my personal access token (owner) containing all possible permissions
