### ISSUE TITLE
Danger crash on start with a repository that has more than 2041 branches

### ISSUE THREAD

**Issue by danielgomezrico** [danger/danger#1344]
# Report

## What did you do?

Having a repository with `2041` branches, the danger script does not load and it crash.

I just added this to with https://github.com/MeilCli/danger-action, the hole github action setup is:

```yaml
name: PR Metadata Checks

on:
  pull_request:
    types: [opened, edited, synchronize]

# Cancel jobs and just run the last one
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request' # if only run pull request when multiple trigger workflow
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.8 # Not needed with a .ruby-version file
        bundler-cache: false # runs 'bundle install' and caches installed gems automatically
        bundler: 2.3.3
    - uses: MeilCli/danger-action@v5
      with:
        plugins_file: '.github/Gemfile'
        install_path: 'vendor/bundle'
        danger_file: '.github/Dangerfile'
        danger_id: 'danger-pr'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
``` 

## What did you expect to happen?

It should run fine

## What happened instead?

ℹ Please replace this with of what happened instead.
Crash:

```bash
bundler: failed to load command: danger (/home/runner/work/app-client-flutter/app-client-flutter/vendor/bundle/ruby/2.6.0/bin/danger)
/home/runner/work/app-client-flutter/app-client-flutter/vendor/bundle/ruby/2.6.0/gems/danger-8.4.2/lib/danger/scm_source/git_repo.rb:138:in `find_merge_base': Cannot find a merge base between danger_base and danger_head. If you are using shallow clone/fetch, try increasing the --depth (RuntimeError)
	from /home/runner/work/app-client-flutter/app-client-flutter/vendor/bundle/ruby/2.6.0/gems/danger-8.4.2/lib/danger/scm_source/git_repo.rb:22:in `diff_for_folder'
	from /home/runner/work/app-client-flutter/app-client-flutter/vendor/bundle/ruby/2.6.0/gems/danger-8.4.2/lib/danger/danger_core/dangerfile.rb:274:in `setup_for_running'
	from /home/runner/work/app-client-flutter/app-client-flutter/vendor/bundle/ruby/2.6.0/gems/danger-8.4.2/lib/danger/danger_core/dangerfile.rb:284:in `run'
	from /home/runner/work/app-client-flutter/app-client-flutter/vendor/bundle/ruby/2.6.0/gems/danger-8.4.2/lib/danger/danger_core/executor.rb:29:in `run'
	from /home/runner/work/app-client-flutter/app-client-flutter/vendor/bundle/ruby/2.6.0/gems/danger-8.4.2/lib/danger/commands/runner.rb:73:in `run'
	from /home/runner/work/app-client-flutter/app-client-flutter/vendor/bundle/ruby/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
	from /home/runner/work/app-client-flutter/app-client-flutter/vendor/bundle/ruby/2.6.0/gems/danger-8.4.2/bin/danger:5:in `<top (required)>'
	from /home/runner/work/app-client-flutter/app-client-flutter/vendor/bundle/ruby/2.6.0/bin/danger:23:in `load'
	from /home/runner/work/app-client-flutter/app-client-flutter/vendor/bundle/ruby/2.6.0/bin/danger:23:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:58:in `load'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.3/lib/bundler/cli.rb:484:in `exec'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.3/lib/bundler/cli.rb:31:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.3/lib/bundler/cli.rb:25:in `start'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.3/exe/bundle:48:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.3/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/bundler-2.3.3/exe/bundle:36:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/bin/bundle:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.6.8/x64/bin/bundle:23:in `<main>'
```

## Your Environment

* Which CI are you running on? Github Action
* Are you running the latest version of Danger?  8.4.2
* What is your Dangerfile?

  ```ruby
def warn_lint
    flutter_lint.only_modified_files = true
    flutter_lint.report_path = "flutter_analyze_report.txt"
    flutter_lint.lint(inline_mode: true)
end

begin
    warn_lint
rescue => e
    warn "Something pretty bad happened running the Dangerfile :( #{e}"
end
  ```
