### ISSUE TITLE
Not a Drone Pull Request - skipping `danger` run

### ISSUE THREAD

**Issue by scottyab** [danger/danger#1373]
# Report

## What did you do?

Added the following to my Drone.yml in the default pipeline

```
 - name: run Danger PR validator
    image: dangersystems/danger-rb
    depends_on:
      - test
    commands:
      - bundle exec danger --fail-on-errors=true --new-comment --remove-previous-comments
    environment:
      DANGER_GITHUB_API_TOKEN:
        from_secret: DANGER_GITHUB_API_TOKEN
    when:
      event:
        include:
          - push
          - pull_request
```          

## What did you expect to happen?

Created a PR and expected Danger to run and analyse the Pull Request

## What happened instead?

Console log from the " run Danger PR validator" Drone step
```
latest: Pulling from dangersystems/danger-rb
Digest: sha256: blahblahblah
Status: Downloaded newer image for dangersystems/danger-rb:latest
+ bundle exec danger --fail-on-errors=true --new-comment --remove-previous-comments
Not a Drone Pull Request - skipping `danger` run.
```

## Your Environment

* Which CI are you running on? DroneCI
* Are you running the latest version of Danger? 8.6.1 
* What is your Dangerfile?  I'm just trying to get this hooked up to Drone so ATM my danger file is just

  ```ruby
info("Hello from Danger :) ")
  ```
