### ISSUE TITLE
Danger builds not-inline report with wrong links

### ISSUE THREAD

**Issue by bartwell** [danger/danger#1389]
# Report

## What did you do?

Run `danger --verbose --dangerfile=Dangerfile --danger_id=danger-pr`

## What did you expect to happen?

Danger will post inline comments with violations.

## What happened instead?

Danger post just one comment (not inline) with the list of violations. All links in this post are broken (when I click it I see 404 Not Found). Example of the link: https://github.com/my_organization/my_repo_name/blob/4a705484d1432997248b461665144d6420fc2ccd/src/main/java/com/my_app_name/app_module_name/path/to/file/SomeKotlinClass.kt#L79

## Your Environment

* I am running it using GitHub Actions
* I am using Danger 9.0

My Dangerfile:
  ```ruby
# Only focus on changes for the current DIFF from the active PR
# github.dismiss_out_of_range_messages

has_wip_label = github.pr_labels.any? { |label| label.include? "Engineers at work" }
has_wip_title = github.pr_title.include? "[WIP]"
if has_wip_label || has_wip_title
	warn("PR is marked as Work in Progress")
end

fail("PR specifies label DO NOT MERGE") if github.pr_labels.any? { |label| label.include? "DO NOT MERGE" }

warn("Big PR") if git.lines_of_code > 5000

detektFile = String.new("/home/runner/work/my_repo_name/my_repo_name/app_module_name/build/reports/detekt/playMarketDevDebug.xml")
if File.file?(detektFile)
    kotlin_detekt.report_file = detektFile
    kotlin_detekt.skip_gradle_task = true
    kotlin_detekt.severity = "warning"
    kotlin_detekt.filtering = false
    kotlin_detekt.detekt(inline_mode: true)
else
    warn("No Detekt report found")
end
  ```

My workflow file:
  ```
name: Review PR with Danger

on:
  pull_request:
    branches: ["develop"]
    types: [opened, synchronize, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Clone main repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble debug build
        run: ./gradlew clean assemblePlayMarketDevDebug

      - name: Run Detekt
        run: ./gradlew detektPlayMarketDevDebug

      - name: Run Danger
        run: |
          gem install danger
          bundle exec danger --verbose --dangerfile=Dangerfile --danger_id=danger-pr
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.REPO_KEY }}
  ```
