### ISSUE TITLE
danger Action fails on POST

### ISSUE THREAD

**Issue by jaymzh** [danger/danger#1462]
# Report

## What did you do?

Use the GH action thusly:

```yaml
  danger:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: danger/danger@master
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## What did you expect to happen?

It to work. Note that if I do a "bundle exec danger" instead, it does work.

## What happened instead?

```
bundler: failed to load command: danger (/usr/local/bundle/bin/danger)
/usr/local/bundle/gems/octokit-7.2.0/lib/octokit/response/raise_error.rb:14:in `on_complete': POST https://api.github.com/repos/chef/chef/issues/13976/comments: 403 - Resource not accessible by integration // See: https://docs.github.com/rest/issues/comments#create-an-issue-comment (Octokit::Forbidden)
```

## Your Environment

* Which CI are you running on? GH Actions
* Are you running the latest version of Danger? Yes
* What is your Dangerfile?

  ```ruby
# Enforce our Gemfile update policy
if git.modified_files.include?('Gemfile.lock')
  if git.modified_files.include?('Gemfile')
    message "PR updates Gemfile.lock, but it also updates Gemfile, so that" +
      " is probably OK - but the reviewer should check updates are soley" +
      " from the Gemfile update"
  elsif !github.pr_body.include?('--conservative')
    if github.pr_body.include?("#gemlock_major_upgrade")
      message "PR updates Gemfile.lock, but output doesn't appear to be in" +
          " the PR Description. However #gemlock_major_upgrade does, so allowing"
    else
      failure "Gem/Bundle changes were not documented in the Description. If" +
        " this is a major update, add #gemlock_major_upgrade to the PR"
        " Description."
    end
  end
end
```
